force-app/main/default/objects/Individual_Yacht__c/Individual_Yacht__c.object-meta.xml
<CustomObject>
    <label>Individual Yacht</label>
    <nameField>
        <label>Yacht Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individual Yachts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Individual_Yacht__c/fields/Yacht_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Yacht_External_ID__c</fullName>
    <externalId>true</externalId>
    <label>Yacht External ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Logs__c/Integration_Logs__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Integration Logs No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Logs__c/fields/Integration_Type__c.field-meta.xml
<CustomField>
    <fullName>Integration_Type__c</fullName>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Reservation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Logs__c/fields/Request_Payload__c.field-meta.xml
<CustomField>
    <fullName>Request_Payload__c</fullName>
    <label>Request Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Logs__c/fields/Yacht_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Yacht_Reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Yacht Reservation</label>
    <referenceTo>Yacht_Reservation__c</referenceTo>
    <relationshipLabel>Integration Logs</relationshipLabel>
    <relationshipName>Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Yacht_Reservation__c/Yacht_Reservation__c.object-meta.xml
<CustomObject>
    <label>Yacht Reservation</label>
    <nameField>
        <displayFormat>RA-{000000}</displayFormat>
        <label>Yacht Reservation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Yacht Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Yacht_Reservation__c/fields/Individual_Yacht__c.field-meta.xml
<CustomField>
    <fullName>Individual_Yacht__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Individual Yacht</label>
    <referenceTo>Individual_Yacht__c</referenceTo>
    <relationshipLabel>Yacht Reservations</relationshipLabel>
    <relationshipName>Yacht_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Yacht_Reservation__c/fields/Party_Size__c.field-meta.xml
<CustomField>
    <fullName>Party_Size__c</fullName>
    <label>Party Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Yacht_Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/YachtReservationHelperClass.cls
public without sharing class YachtReservationHelperClass {
    
    public static void createReservationInExternalSystem(Id reservationId){

        try{
        List<Yacht_Reservation__c> reservation = [select id,Individual_Yacht__c,name,Guest_Email__c,Party_Size__c,Reservation_Date__c,Guest_Name__c,Individual_Yacht__r.Yacht_External_ID__c from Yacht_Reservation__c where id =: reservationId with SECURITY_ENFORCED];
            
           
            if(!reservation.isEmpty() && reservation[0].id != null){
            System.enqueueJob(
                    new YachtReservationQueueable(
                        reservation[0].id,
                        reservation[0].Guest_Email__c,
                        reservation[0].Guest_Name__c,
                        reservation[0].Individual_Yacht__r.Yacht_External_ID__c,
                        reservation[0].Party_Size__c,
                        reservation[0].Reservation_Date__c,
                        'Confirmed')
                    );
            }
        }
        catch(Exception e){
            System.debug('Exception ::' + e.getMessage());
            createIntegrationlogs('Reservation', reservationId, '', '', '', e.getMessage());            
        }
    }

    public static void createIntegrationlogs(
        String IntegrationType,
        Id reservationId,
        String requestPayload,
        String responsePayload,
        String errorCode,
        String errorMessage){
            try{
                Integration_Logs__c il = new Integration_Logs__c();
                il.Integration_Type__c = IntegrationType;
                il.Status__c = 'Failed';
                il.Request_Payload__c = requestPayload;
                il.Error_Message__c = errorMessage;
                il.Error_Code__c = errorCode;
                if(IntegrationType == 'Reservation' && reservationId != null){
                    il.Yacht_Reservation__c = reservationId;
                }
                il.Response_Payload__c = responsePayload;
                Database.insert(new List<Integration_Logs__c>{ il }, AccessLevel.USER_MODE);
            }
            catch(Exception e){
                System.debug(' createIntegrationlogs Exception ::' + e.getMessage());
            }
        }

}